const SPREADSHEET_ID = '1-3LtAbXZU6klisReK6ffIxDUwbM4wXvhxSbKVpE7raY';
const CATEGORIES = ['NSC','DISCONNECTION','METER_REPLESMENT','POLE_CASE','DTR_REPLESMENT'];
const COMMON = ['id','category','status','date','createdAt','workerName','workerPhone','substation','feederName','consumerId','consumerName','fatherName','applicationNo','agencyName','cccName','mobile','address','poleNo','appliedLoad','phase','tariffCategory','meterNo','initialReading','sealNo','serviceCableLength','meterInstallDate','inspectionAgencyName','meterMake','workOrderNo','workOrderDate','arrearAmount','reason','finalReading','disconnectionType','cutoutSealed','issueType','priority','actionTaken','materialUsed','poleType','lineVoltage','conductorType','ptwShutdownRef','oldMeterNo','replacementReason','newMeterNo','newMeterSealNo','oldMeterSealNo','meterType','dtrName','existingCapacity','newCapacity','oldDtrSerial','newDtrSerial','failureReason','oilLevelChecked','earthResistance','dtrMakeBrand','hgFuseRating','ltMccbAmpere','lightningArrester','locationGps','photoUrl','photoBeforeUrl','photoAfterUrl','workOrderPhoto','workOrderNoticeId','workOrderNoticeTitle','workOrderNoticeDate','notes','updatedAt'];
const USER_HEADERS = ['id','idNo','passwordHash','name','phone','role','status','designation','badgeNo','securityQuestion','securityAnswerHash','createdAt','updatedAt'];
const WORK_HEADERS = ['id','category','title','photoUrl','description','uploadedBy','adminName','adminPhone','uploadDate','uploadTime','createdAt','isHidden'];
const CHAT_HEADERS = ['id','workerId','senderId','senderName','senderRole','recipientId','recipientRole','message','timestamp','status','createdAt'];

function ss(){ return SpreadsheetApp.openById(SPREADSHEET_ID); }
function sheet(name, headers){ let s=ss().getSheetByName(name); if(!s)s=ss().insertSheet(name); if(s.getLastRow()===0 || s.getRange(1,1).getValue()!==headers[0]) s.getRange(1,1,1,headers.length).setValues([headers]); s.setFrozenRows(1); return s; }
function setupDatabase(){ sheet('Users',USER_HEADERS); sheet('Entries',COMMON); CATEGORIES.forEach(x=>sheet(x,COMMON)); sheet('WorkOrders',WORK_HEADERS); sheet('Chat',CHAT_HEADERS); return {success:true,spreadsheetId:SPREADSHEET_ID,spreadsheetUrl:ss().getUrl()}; }
function headersFor(name){ if(name==='Users')return USER_HEADERS; if(name==='WorkOrders')return WORK_HEADERS; if(name==='Chat')return CHAT_HEADERS; return COMMON; }
function rows(name){ const s=sheet(name,headersFor(name)); const n=s.getLastRow(), c=s.getLastColumn(); if(n<2)return []; const h=s.getRange(1,1,1,c).getValues()[0]; return s.getRange(2,1,n-1,c).getValues().map(r=>{const o={};h.forEach((k,i)=>o[k]=r[i]);return o;}); }
function add(name,obj){ const h=headersFor(name), s=sheet(name,h); s.appendRow(h.map(k=>obj[k]===undefined?'':obj[k])); return obj; }
function sha(v){ return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(v||''),Utilities.Charset.UTF_8).map(b=>(b<0?b+256:b).toString(16).padStart(2,'0')).join(''); }
function id(p){return p+'-'+Date.now()+'-'+Math.random().toString(36).slice(2,8);}
function now(){return new Date().toISOString();}
function out(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON);}
function findIndex(name,key,value){ const s=sheet(name,headersFor(name)), h=headersFor(name), idx=h.indexOf(key); if(idx<0)return -1; const n=s.getLastRow(); if(n<2)return -1; const vals=s.getRange(2,idx+1,n-1,1).getValues(); for(let i=0;i<vals.length;i++)if(String(vals[i][0])===String(value))return i+2; return -1; }
function update(name,key,value,data){ const s=sheet(name,headersFor(name)), h=headersFor(name), r=findIndex(name,key,value); if(r<0)throw Error('Record not found'); const old={}; h.forEach((k,i)=>old[k]=s.getRange(r,i+1).getValue()); Object.assign(old,data); h.forEach((k,i)=>s.getRange(r,i+1).setValue(old[k]===undefined?'':old[k])); return old; }
function remove(name,key,value){ const s=sheet(name,headersFor(name)),r=findIndex(name,key,value); if(r<0)throw Error('Record not found'); s.deleteRow(r); return true; }

function createUser(d){ const users=rows('Users'); if(users.some(u=>String(u.idNo).toLowerCase()===String(d.idNo).toLowerCase()))throw Error('User ID already exists'); const u={id:d.id||id('USR'),idNo:d.idNo||'',passwordHash:sha(d.password||''),name:d.name||d.idNo||'কর্মী',phone:d.phone||'',role:d.role||'worker',status:d.status||'active',designation:d.designation||'',badgeNo:d.badgeNo||d.idNo||'',securityQuestion:d.securityQuestion||'',securityAnswerHash:sha(d.securityAnswer||''),createdAt:now(),updatedAt:''}; add('Users',u); delete u.passwordHash; delete u.securityAnswerHash; return u; }
function safeUser(u){const x=Object.assign({},u);delete x.passwordHash;delete x.securityAnswerHash;return x;}
function login(idNo,password){ const u=rows('Users').find(x=>String(x.idNo).toLowerCase()===String(idNo).toLowerCase()); if(!u)throw Error('Invalid User ID or Password'); if(u.status==='hold')throw Error('Account is on hold'); if(String(u.passwordHash)!==sha(password))throw Error('Invalid User ID or Password'); return {id:u.id,idNo:u.idNo,name:u.name,phone:u.phone,role:u.role,status:u.status,designation:u.designation,badgeNo:u.badgeNo,loggedInAt:now()}; }
function createEntry(d){ const e=Object.assign({},d,{id:d.id||id('PWR'),status:d.status||'Completed',date:d.date||now(),createdAt:d.createdAt||now(),updatedAt:now()}); add('Entries',e); const cat=String(e.category||'').toUpperCase(); if(CATEGORIES.indexOf(cat)>=0)add(cat,e); return e; }
function filterEntries(p){ let a=rows('Entries'); if(p.category&&p.category!=='ALL')a=a.filter(x=>String(x.category).toUpperCase()===String(p.category).toUpperCase()); if(p.status&&p.status!=='ALL')a=a.filter(x=>String(x.status).toLowerCase()===String(p.status).toLowerCase()); if(p.search){const q=String(p.search).toLowerCase();a=a.filter(x=>JSON.stringify(x).toLowerCase().indexOf(q)>=0);} return a.reverse(); }
function stats(){const a=rows('Entries'); const c=n=>a.filter(x=>String(x.category).toUpperCase()===n).length; return {total:a.length,categories:{NSC:c('NSC'),DISCONNECTION:c('DISCONNECTION'),'POLE CASE':c('POLE CASE'),METER_REPLESMENT:c('METER REPLESMENT'),DTR_REPLESMENT:c('DTR REPLESMENT')},status:{pending:a.filter(x=>x.status==='Pending').length,completed:a.filter(x=>x.status==='Completed').length,approved:a.filter(x=>x.status==='Approved').length}};}
function createWork(d){const x={id:d.id||id('WO'),category:d.category||'NSC',title:d.title||'Work Order / Khata Notice',photoUrl:d.photoUrl||'',description:d.description||'',uploadedBy:d.uploadedBy||'',adminName:d.adminName||'',adminPhone:d.adminPhone||'',uploadDate:Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'dd MMM yyyy'),uploadTime:Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'hh:mm a'),createdAt:now(),isHidden:Boolean(d.isHidden)};add('WorkOrders',x);return x;}
function doGet(e){try{setupDatabase();const p=e.parameter||{},a=p.action||'health';if(a==='health')return out({success:true,status:'ok',app:'WB POWER APP',message:'Google Sheets API is working'});if(a==='database')return out({success:true,spreadsheetId:SPREADSHEET_ID,spreadsheetUrl:ss().getUrl()});if(a==='users')return out({success:true,users:rows('Users').map(safeUser)});if(a==='entries')return out({success:true,entries:filterEntries(p)});if(a==='stats')return out({success:true,stats:stats()});if(a==='verify'){const u=rows('Users').find(x=>String(x.idNo).toLowerCase()===String(p.idNo||'').toLowerCase());return out({success:true,result:u?{valid:u.status==='active',status:u.status}:{valid:false,error:'User not found'}});}if(a==='chat'){let m=rows('Chat');if(p.workerId)m=m.filter(x=>String(x.workerId)===String(p.workerId));return out({success:true,messages:m});}if(a==='workorders'){let w=rows('WorkOrders');if(p.category&&p.category!=='ALL')w=w.filter(x=>x.category===p.category||x.category==='ALL');return out({success:true,workOrders:w.reverse()});}throw Error('Unknown API action');}catch(err){return out({success:false,error:String(err.message||err)});}}
function doPost(e){try{setupDatabase();const b=JSON.parse((e.postData&&e.postData.contents)||'{}'),a=b.action,d=b.data||{};if(a==='setup')return out(setupDatabase());if(a==='login')return out({success:true,session:login(b.idNo,b.password)});if(a==='createUser')return out({success:true,user:createUser(d)});if(a==='updateUser')return out({success:true,user:safeUser(update('Users','id',b.id,d))});if(a==='deleteUser')return out({success:remove('Users','id',b.id)});if(a==='updateUserStatus')return out({success:true,user:safeUser(update('Users','id',b.id,{status:b.status,updatedAt:now()}))});if(a==='changePassword'){const u=rows('Users').find(x=>String(x.idNo).toLowerCase()===String(b.idNo).toLowerCase());if(!u||u.passwordHash!==sha(b.currentPassword))throw Error('Current password is incorrect');update('Users','id',u.id,{passwordHash:sha(b.newPassword),updatedAt:now()});return out({success:true});}if(a==='resetPassword'){const u=rows('Users').find(x=>String(x.idNo).toLowerCase()===String(b.idNo).toLowerCase()&&(!b.phone||String(x.phone).replace(/\D/g,'')===String(b.phone).replace(/\D/g,'')));if(!u)throw Error('User not found');update('Users','id',u.id,{passwordHash:sha(b.newPassword),updatedAt:now()});return out({success:true});}if(a==='createEntry')return out({success:true,entry:createEntry(d)});if(a==='updateEntry')return out({success:true,entry:update('Entries','id',b.id,d)});if(a==='deleteEntry')return out({success:remove('Entries','id',b.id)});if(a==='clearEntries'){const s=sheet('Entries',COMMON);if(s.getLastRow()>1)s.deleteRows(2,s.getLastRow()-1);return out({success:true});}if(a==='sendChat'){const x=Object.assign({},d,{id:d.id||id('CHAT'),timestamp:d.timestamp||now(),status:d.status||'sent',createdAt:now()});return out({success:true,message:add('Chat',x)});}if(a==='clearChat'){const s=sheet('Chat',CHAT_HEADERS);if(s.getLastRow()>1)s.deleteRows(2,s.getLastRow()-1);return out({success:true});}if(a==='createWorkOrder')return out({success:true,workOrder:createWork(d)});if(a==='toggleWorkOrder')return out({success:update('WorkOrders','id',b.id,{isHidden:Boolean(b.isHidden)})});if(a==='deleteWorkOrder')return out({success:remove('WorkOrders','id',b.id)});throw Error('Unknown POST action');}catch(err){return out({success:false,error:String(err.message||err)});}}
