import React, { useState } from 'react';
import appLogo from '../assets/images/power_round_logo_1787860440979.jpg';
import { 
  X, 
  ShieldCheck, 
  Lock, 
  AlertTriangle, 
  FileSpreadsheet, 
  PhoneCall, 
  Download, 
  Printer, 
  CheckSquare, 
  Radio, 
  HelpCircle,
  Database,
  Sparkles,
  Zap,
  KeyRound,
  CheckCircle2,
  HardHat
} from 'lucide-react';
import { CornerOptionKey, PowerEntry } from '../types';

interface CornerOptionsModalProps {
  activeOption: CornerOptionKey;
  onClose: () => void;
  isAdmin: boolean;
  onLoginAdmin: (pin: string) => boolean;
  onLogoutAdmin: () => void;
  onSwitchToAdminTab: () => void;
  entries: PowerEntry[];
  onExportCsv: () => void;
}

export const CornerOptionsModal: React.FC<CornerOptionsModalProps> = ({
  activeOption,
  onClose,
  isAdmin,
  onLoginAdmin,
  onLogoutAdmin,
  onSwitchToAdminTab,
  entries,
  onExportCsv,
}) => {
  const [adminPin, setAdminPin] = useState('');
  const [pinError, setPinError] = useState(false);
  const [safetyChecklist, setSafetyChecklist] = useState({
    lineIsolated: true,
    earthGrounded: true,
    safetyGearEquipped: true,
    ptwSigned: false,
    dischargingTested: true,
  });

  if (!activeOption) return null;

  const handleAdminPinSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const success = onLoginAdmin(adminPin);
    if (success) {
      setPinError(false);
      setAdminPin('');
      onSwitchToAdminTab();
      onClose();
    } else {
      setPinError(true);
    }
  };

  const handlePrintDailySummary = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const todayStr = new Date().toLocaleDateString('bn-BD');
    const nscCount = entries.filter(e => e.category === 'NSC').length;
    const discCount = entries.filter(e => e.category === 'DISCONNECTION').length;
    const poleCount = entries.filter(e => e.category === 'POLE CASE').length;
    const meterCount = entries.filter(e => e.category === 'METER REPLESMENT').length;
    const dtrCount = entries.filter(e => e.category === 'DTR REPLESMENT').length;

    const content = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>POWER Daily Field Summary Sheet - ${todayStr}</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 25px; color: #111; }
          .header { border-bottom: 2px solid #b45309; padding-bottom: 10px; margin-bottom: 15px; }
          .title { font-size: 22px; font-weight: bold; color: #92400e; }
          .stats { display: flex; gap: 10px; margin-bottom: 15px; }
          .stat-box { border: 1px solid #ddd; padding: 8px 12px; border-radius: 6px; font-size: 12px; }
          table { width: 100%; border-collapse: collapse; margin-top: 15px; font-size: 12px; }
          th, td { border: 1px solid #ccc; padding: 6px 8px; text-align: left; }
          th { background: #f3f4f6; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="title">⚡ POWER - Daily Electric Utility Log Summary</div>
          <div>Date: ${todayStr} | Generated by Admin Portal</div>
        </div>
        <div class="stats">
          <div class="stat-box"><strong>Total:</strong> ${entries.length}</div>
          <div class="stat-box"><strong>NSC:</strong> ${nscCount}</div>
          <div class="stat-box"><strong>Disconnection:</strong> ${discCount}</div>
          <div class="stat-box"><strong>Pole Case:</strong> ${poleCount}</div>
          <div class="stat-box"><strong>Meter Rep.:</strong> ${meterCount}</div>
          <div class="stat-box"><strong>DTR Rep.:</strong> ${dtrCount}</div>
        </div>
        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>Category</th>
              <th>Consumer / Site</th>
              <th>Worker Name</th>
              <th>Feeder / Pole</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            ${entries.map(e => `
              <tr>
                <td>${e.id}</td>
                <td><strong>${e.category}</strong></td>
                <td>${e.consumerName || e.dtrName || e.poleNo || '-'}</td>
                <td>${e.workerName}</td>
                <td>${e.feederName || '-'}</td>
                <td>${e.status}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </body>
      </html>
    `;
    printWindow.document.write(content);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-3 sm:p-4 animate-in fade-in duration-150">
      <div className="bg-white border border-slate-200 rounded-xl w-full max-w-lg shadow-2xl overflow-hidden animate-in zoom-in-95 duration-150">
        {/* Modal Top Header */}
        <div className="px-5 py-4 bg-slate-50 border-b border-slate-200 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <img 
              src={appLogo} 
              alt="Power of Construction Round Logo" 
              className="w-9 h-9 rounded-full object-cover shadow-xs border border-amber-400 p-0.5 bg-white shrink-0"
              referrerPolicy="no-referrer"
            />
            <div>
              <div className="text-[11px] font-bold text-amber-700 uppercase tracking-wider">
                POWER OF CONSTRUCTION
              </div>
              <div className="text-sm font-bold text-slate-900">
                {activeOption === 'admin_portal' && '১. এডমিন পোর্টাল ও সিকিউরিটি লগইন'}
                {activeOption === 'emergency_safety' && '২. জরুরী হেল্পলাইন ও সেফটি নির্দেশিকা'}
                {activeOption === 'export_reports' && '৩. ডাটা এক্সপোর্ট ও দৈনিক রিপোর্ট'}
              </div>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 rounded-lg bg-white hover:bg-slate-100 border border-slate-200 text-slate-500 hover:text-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Option 1: Admin Portal & Login */}
        {activeOption === 'admin_portal' && (
          <div className="p-5 space-y-4">
            {isAdmin ? (
              <div className="space-y-4">
                <div className="p-4 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 flex items-start gap-3">
                  <ShieldCheck className="w-6 h-6 text-emerald-600 shrink-0" />
                  <div>
                    <h3 className="font-bold text-emerald-950 text-sm">এডমিন মোড সক্রিয় আছে!</h3>
                    <p className="text-xs text-emerald-700 mt-1">
                      আপনি বর্তমানে এডমিন হিসেবে লগইন আছেন। ফিল্ড কর্মীদের প্রেরিত মোট {entries.length} টি এন্ট্রি দেখতে পারেন।
                    </p>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-3 pt-2">
                  <button
                    id="goto-admin-dash-btn"
                    onClick={() => {
                      onSwitchToAdminTab();
                      onClose();
                    }}
                    className="w-full py-2.5 bg-slate-900 hover:bg-slate-800 text-white font-bold rounded-lg text-xs flex items-center justify-center gap-1.5 shadow-xs"
                  >
                    <ShieldCheck className="w-4 h-4 text-emerald-400" />
                    <span>এডমিন ড্যাশবোর্ডে যান</span>
                  </button>

                  <button
                    onClick={() => {
                      onLogoutAdmin();
                      onClose();
                    }}
                    className="w-full py-2.5 bg-rose-50 hover:bg-rose-100 text-rose-700 font-bold rounded-lg text-xs flex items-center justify-center gap-1.5 border border-rose-200"
                  >
                    <span>এডমিন লগআউট</span>
                  </button>
                </div>
              </div>
            ) : (
              <form onSubmit={handleAdminPinSubmit} className="space-y-4">
                <div className="text-xs text-slate-600 leading-relaxed">
                  এডমিন প্যানেলে প্রবেশ করে সমস্ত ফিল্ড কর্মীদের জমা দেওয়া ডাটা দেখতে ও অনুমোদন দিতে ৪-সংখ্যার এডমিন পিন কোড দিন।
                </div>

                <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 space-y-3">
                  <label className="block text-xs font-semibold text-slate-700">
                    এডমিন পিন কোড (Admin PIN / Password)
                  </label>
                  <div className="relative">
                    <KeyRound className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
                    <input
                      id="admin-pin-input"
                      type="password"
                      maxLength={8}
                      value={adminPin}
                      onChange={(e) => {
                        setAdminPin(e.target.value);
                        setPinError(false);
                      }}
                      placeholder="ডিফল্ট পিনঃ 1234"
                      className="w-full bg-white border border-slate-200 rounded-lg pl-9 pr-3 py-2.5 text-sm text-slate-900 focus:outline-none focus:ring-2 focus:ring-slate-900/10 focus:border-slate-900 font-mono tracking-widest"
                      autoFocus
                    />
                  </div>

                  {pinError && (
                    <p className="text-xs text-rose-600 font-medium">
                      ❌ ভুল পিন কোড! সঠিক এডমিন পিন দিন।
                    </p>
                  )}
                </div>

                <div className="flex gap-2 pt-2">
                  <button
                    id="admin-login-submit"
                    type="submit"
                    className="flex-1 py-2.5 bg-slate-900 hover:bg-slate-800 text-white font-bold rounded-lg text-xs flex items-center justify-center gap-1.5 shadow-xs"
                  >
                    <Lock className="w-4 h-4 text-amber-400" />
                    <span>এডমিন লগইন করুন</span>
                  </button>
                  <button
                    type="button"
                    onClick={onClose}
                    className="px-4 py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-lg text-xs font-bold border border-slate-200"
                  >
                    বাতিল
                  </button>
                </div>
              </form>
            )}
          </div>
        )}

        {/* Option 2: Emergency SOS & Line Safety Desk */}
        {activeOption === 'emergency_safety' && (
          <div className="p-5 space-y-4 max-h-[75vh] overflow-y-auto">
            {/* Emergency Hotline Numbers */}
            <div className="bg-rose-50/70 border border-rose-200 p-4 rounded-xl space-y-3">
              <div className="flex items-center gap-2 text-rose-800 font-bold text-xs uppercase tracking-wider">
                <PhoneCall className="w-4 h-4 text-rose-600" />
                <span>বিদ্যুৎ জরুরী নিয়ন্ত্রণ কক্ষ (Emergency Hotline)</span>
              </div>

              <div className="grid grid-cols-2 gap-2">
                <a 
                  href="tel:19123"
                  className="bg-white p-2.5 rounded-lg border border-rose-200 text-center hover:bg-rose-50 transition-colors block shadow-2xs"
                >
                  <div className="text-[10px] text-slate-500">বিদ্যুৎ হেল্পলাইন</div>
                  <div className="text-base font-black text-rose-700 font-mono">19123 / 16116</div>
                </a>

                <a 
                  href="tel:999"
                  className="bg-white p-2.5 rounded-lg border border-rose-200 text-center hover:bg-rose-50 transition-colors block shadow-2xs"
                >
                  <div className="text-[10px] text-slate-500">জাতীয় জরুরী সেবা</div>
                  <div className="text-base font-black text-slate-900 font-mono">999 / 112</div>
                </a>
              </div>
            </div>

            {/* Lineman Safety Protocol - Permit to Work */}
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 space-y-3">
              <div className="flex items-center gap-2 text-slate-900 font-bold text-xs uppercase tracking-wider">
                <HardHat className="w-4 h-4 text-amber-600" />
                <span>লাইনম্যান নিরাপত্তা চেকলিস্ট (PTW Safety Rules)</span>
              </div>

              <div className="space-y-2 text-xs text-slate-700">
                <label className="flex items-center gap-2.5 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={safetyChecklist.lineIsolated}
                    onChange={(e) => setSafetyChecklist({ ...safetyChecklist, lineIsolated: e.target.checked })}
                    className="rounded border-slate-300 text-slate-900 focus:ring-slate-900"
                  />
                  <span>১. ফিডার শাটডাউন ও লাইন আইসোলেশন নিশ্চিত করা হয়েছে</span>
                </label>

                <label className="flex items-center gap-2.5 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={safetyChecklist.earthGrounded}
                    onChange={(e) => setSafetyChecklist({ ...safetyChecklist, earthGrounded: e.target.checked })}
                    className="rounded border-slate-300 text-slate-900 focus:ring-slate-900"
                  />
                  <span>২. উভয় পাশে ডিসচার্জ রড দিয়ে শর্ট-সার্কিট আর্থিং সম্পন্ন</span>
                </label>

                <label className="flex items-center gap-2.5 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={safetyChecklist.safetyGearEquipped}
                    onChange={(e) => setSafetyChecklist({ ...safetyChecklist, safetyGearEquipped: e.target.checked })}
                    className="rounded border-slate-300 text-slate-900 focus:ring-slate-900"
                  />
                  <span>৩. হেলমেট, সেফটি বেল্ট ও ৩৩কেভি গ্লাভস পরিধান নিশ্চিত</span>
                </label>

                <label className="flex items-center gap-2.5 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={safetyChecklist.ptwSigned}
                    onChange={(e) => setSafetyChecklist({ ...safetyChecklist, ptwSigned: e.target.checked })}
                    className="rounded border-slate-300 text-slate-900 focus:ring-slate-900"
                  />
                  <span>৪. সাব-স্টেশন অপারেটরের পারমিট-টু-ওয়ার্ক (PTW) স্লিপ গ্রহণ</span>
                </label>
              </div>
            </div>

            <button
              onClick={onClose}
              className="w-full py-2.5 bg-slate-100 hover:bg-slate-200 border border-slate-200 text-slate-700 font-bold rounded-lg text-xs"
            >
              বন্ধ করুন
            </button>
          </div>
        )}

        {/* Option 3: Export & Daily Reports */}
        {activeOption === 'export_reports' && (
          <div className="p-5 space-y-4">
            <div className="text-xs text-slate-600 leading-relaxed">
              POWER অ্যাপের تمام ফিল্ড ডাটা ব্যাকআপ নিন, এক্সেলে ডাউনলোড করুন অথবা দৈনিক শিট প্রিন্ট করুন।
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <button
                id="corner-export-csv"
                onClick={() => {
                  onExportCsv();
                  onClose();
                }}
                className="p-3.5 bg-slate-50 hover:bg-white rounded-xl border border-slate-200 hover:border-emerald-300 text-left space-y-1.5 transition-all shadow-2xs group"
              >
                <div className="flex items-center justify-between">
                  <FileSpreadsheet className="w-5 h-5 text-emerald-600" />
                  <span className="text-[10px] text-emerald-700 bg-emerald-50 px-1.5 py-0.5 rounded font-bold border border-emerald-200">.CSV</span>
                </div>
                <div className="font-bold text-xs text-slate-900 group-hover:text-emerald-700">
                  এক্সেল ফাইল ডাউনলোড (CSV)
                </div>
                <div className="text-[10px] text-slate-500">
                  অফিস রেজিস্টার ও এমআইএস রিপোর্টের জন্য
                </div>
              </button>

              <button
                id="corner-print-summary"
                onClick={handlePrintDailySummary}
                className="p-3.5 bg-slate-50 hover:bg-white rounded-xl border border-slate-200 hover:border-amber-300 text-left space-y-1.5 transition-all shadow-2xs group"
              >
                <div className="flex items-center justify-between">
                  <Printer className="w-5 h-5 text-amber-600" />
                  <span className="text-[10px] text-amber-800 bg-amber-50 px-1.5 py-0.5 rounded font-bold border border-amber-200">PRINT</span>
                </div>
                <div className="font-bold text-xs text-slate-900 group-hover:text-amber-700">
                  দৈনিক লগ শিট প্রিন্ট
                </div>
                <div className="text-[10px] text-slate-500">
                  আজকের মোট {entries.length} টি কাজের সংক্ষিপ্ত তালিকা
                </div>
              </button>
            </div>

            {/* Sync diagnostic status */}
            <div className="bg-slate-50 p-3 rounded-xl border border-slate-200 text-xs flex items-center justify-between text-slate-600">
              <div className="flex items-center gap-2">
                <Database className="w-4 h-4 text-slate-600" />
                <span>ডাটাবেজ স্টোরেজ স্থিতি:</span>
              </div>
              <span className="text-emerald-700 font-bold flex items-center gap-1">
                <CheckCircle2 className="w-3.5 h-3.5" /> সার্ভার সিঙ্ক সক্রিয়
              </span>
            </div>

            <button
              onClick={onClose}
              className="w-full py-2.5 bg-slate-100 hover:bg-slate-200 border border-slate-200 text-slate-700 font-bold rounded-lg text-xs"
            >
              বন্ধ করুন
            </button>
          </div>
        )}
      </div>
    </div>
  );
};
